# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 00:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('geo_x', models.DecimalField(decimal_places=16, max_digits=21)),
                ('geo_y', models.DecimalField(decimal_places=16, max_digits=21)),
                ('image', models.ImageField(upload_to='dcim/')),
                ('note', models.TextField(blank=True, null=True)),
                ('flag', models.IntegerField(default=0)),
                ('by', models.ManyToManyField(related_name='images', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('house_number', models.IntegerField()),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('site_plan', models.ImageField(upload_to='sites/')),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('upperleft_geo_x', models.DecimalField(decimal_places=16, max_digits=21)),
                ('upperleft_geo_y', models.DecimalField(decimal_places=16, max_digits=21)),
                ('bottomright_geo_x', models.DecimalField(decimal_places=16, max_digits=21)),
                ('bottomright_geo_y', models.DecimalField(decimal_places=16, max_digits=21)),
                ('upperleft_pix_x', models.DecimalField(decimal_places=16, max_digits=21)),
                ('upperleft_pix_y', models.DecimalField(decimal_places=16, max_digits=21)),
                ('bottomright_pix_x', models.DecimalField(decimal_places=16, max_digits=21)),
                ('bottomright_pix_y', models.DecimalField(decimal_places=16, max_digits=21)),
                ('by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, null=True, to='photobase.Image')),
            ],
        ),
    ]
