# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photobase', '0002_auto_20170318_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coords',
            name='address',
        ),
    ]
