# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 04:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photobase', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('house_number', models.IntegerField()),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sitedoc',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sitedoc',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='sitedoc',
            name='state',
        ),
        migrations.RemoveField(
            model_name='sitedoc',
            name='street',
        ),
        migrations.RemoveField(
            model_name='sitedoc',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='project',
            name='plans',
            field=models.ManyToManyField(blank=True, to='photobase.SiteDoc'),
        ),
    ]
