# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobase', '0005_auto_20170318_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedoc',
            name='bottomright_pix_x',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='sitedoc',
            name='bottomright_pix_y',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='sitedoc',
            name='upperleft_pix_x',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='sitedoc',
            name='upperleft_pix_y',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=21, null=True),
        ),
    ]
