# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobase', '0006_auto_20170319_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedoc',
            name='site_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='sites/img/'),
        ),
        migrations.AlterField(
            model_name='sitedoc',
            name='site_plan',
            field=models.FileField(upload_to='sites/pdf/'),
        ),
    ]
